---
name: Push python

on:
  push:
    branches:
      - main
    paths:
      - src/python/*
  pull_request:
    paths:
      - src/python/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  AWS_ECR_PUBLIC_IMAGE_NAME: python
  AWS_ECR_PUBLIC_REPOSITORY_GROUP: base
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Singapore

jobs:
  build-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          AWS_OIDC_ROLE_ARN: ${{ env.AWS_OIDC_ROLE_ARN }}
          AWS_ECR_PUBLIC_IMAGE_NAME: ${{ env.AWS_ECR_PUBLIC_IMAGE_NAME }}
          AWS_ECR_PUBLIC_REPOSITORY_GROUP: ${{ env.AWS_ECR_PUBLIC_REPOSITORY_GROUP }}

      - name: Extract Version from Dockerfile
        uses: ./.github/actions/apply-tags
        with:
          AWS_ECR_PUBLIC_IMAGE_NAME: ${{ env.AWS_ECR_PUBLIC_IMAGE_NAME }}
          AWS_ECR_PUBLIC_IMAGE_TAG_SCRIPT: tags.sh

      - name: Docker build & push
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./src/${{ env.AWS_ECR_PUBLIC_IMAGE_NAME }}

  dependabot-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set shell options
        run: set -euxo pipefail

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Version from Dockerfile
        uses: ./.github/actions/apply-tags
        with:
          AWS_ECR_PUBLIC_IMAGE_NAME: ${{ env.AWS_ECR_PUBLIC_IMAGE_NAME }}
          AWS_ECR_PUBLIC_IMAGE_TAG_SCRIPT: tags.sh

      - name: Run docker buildx test
        uses: docker/bake-action@v5
        with:
          targets: test
          workdir: ./src/${{ env.AWS_ECR_PUBLIC_IMAGE_NAME }}

      - name: Setup Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Auto-merge for Dependabot PR
        run: gh pr merge --auto --merge "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
